#ifndef __NRF24L01_CONSTANTS_H__
#define __NRF24L01_CONSTANTS_H__ 1



#define COMMAND_R_REGISTER 0
#define COMMAND_W_REGISTER 32
#define COMMAND_R_RX_PAYLOAD 97
#define COMMAND_W_TX_PAYLOAD 160
#define COMMAND_FLUSH_TX 225
#define COMMAND_FLUSH_RX 226
#define COMMAND_NOP 255

#define REGISTER_CONFIG 0
#define REGISTER_EN_AA 1
#define REGISTER_EN_RXADDR 2
#define REGISTER_SETUP_AW 3
#define REGISTER_SETUP_RETR 4
#define REGISTER_RF_CH 5
#define REGISTER_RF_SETUP 6
#define REGISTER_STATUS 7
#define REGISTER_RX_ADDR_P0 10
#define REGISTER_RX_ADDR_P1 11
#define REGISTER_TX_ADDR 16
#define REGISTER_RX_PW_P0 17
#define REGISTER_FIFO_STATUS 23
#define REGISTER_DYNPD 28
#define REGISTER_FEATURE 29

#define BIT_PRIM_RX 1
#define BIT_PWR_UP 2
#define BIT_ERX_P1 2
#define BIT_MAX_RT 16
#define BIT_TX_DS 32
#define BIT_RX_DR 64



#endif
